spring.application.name=cadastro-cliente

spring.datasource.url=jdbc:mysql://localhost:3306/cadastro_clientes
spring.datasource.username=root
spring.datasource.password=Deusefamilia26

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
